# Generated by Django 6.1.1 on 2026-09-30 22:32

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="PaperRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(max_length=32)),
                ("external_id", models.CharField(max_length=64)),
                ("title", models.TextField()),
                ("abstract", models.TextField()),
                ("authors", models.JSONField(default=list)),
                ("published", models.DateField(blank=True, null=True)),
                ("url", models.URLField(blank=True)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(dimensions=768, null=True),
                ),
                (
                    "record_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
            ],
            options={
                "db_table": "paper_records",
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="paper_embedding_hnsw",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "external_id"), name="uniq_source_paper"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NomicEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text_hash", models.CharField(max_length=64)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=768)),
                (
                    "paper",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DB_CASCADE,
                        related_name="+",
                        to="model.paperrecord",
                    ),
                ),
            ],
            options={
                "db_table": "embedding_nomic_embed_text",
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="emb_nomic_hnsw",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BgeM3Embedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text_hash", models.CharField(max_length=64)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1024)),
                (
                    "paper",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DB_CASCADE,
                        related_name="+",
                        to="model.paperrecord",
                    ),
                ),
            ],
            options={
                "db_table": "embedding_bge_m3",
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="emb_bge_m3_hnsw",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
    ]
