# Generated by Django 6.1.1 on 2026-09-26 22:03

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        VectorExtension(),  # Not added automaticaly, but needed
        migrations.CreateModel(
            name="PaperRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(max_length=32)),
                ("external_id", models.CharField(max_length=64)),
                ("title", models.TextField()),
                ("abstract", models.TextField()),
                ("authors", models.JSONField(default=list)),
                ("published", models.DateField(blank=True, null=True)),
                ("url", models.URLField(blank=True)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(dimensions=768, null=True),
                ),
            ],
            options={
                "db_table": "paper_records",
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="paper_embedding_hnsw",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "external_id"), name="uniq_source_paper"
                    )
                ],
            },
        ),
    ]
